# Generated by Django 2.2.10 on 2020-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='group_type',
            field=models.CharField(choices=[('staff_verification', 'staff_verification'), ('staff_cv', 'staff_cv'), ('staff_jobs', 'staff_jobs'), ('staff_blog_creator', 'staff_blog_creator'), ('staff_blog_moderator', 'staff_blog_moderator')], default='staff_verification', max_length=60),
        ),
    ]
