# Generated by Django 2.2.7 on 2019-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='facility_address',
            field=models.CharField(default='defaultadress', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='facility_name',
            field=models.CharField(default='defaultname', max_length=60),
            preserve_default=False,
        ),
    ]
