# Generated by Django 2.2.8 on 2020-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Staff'), (3, 'Employer')], default=1),
        ),
    ]
