# Generated by Django 2.2.10 on 2020-03-24 19:27

import account.account_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200314_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='group_type',
            field=models.CharField(choices=[('staff_verification', 'staff_verification'), (2, 'staff_cv'), (3, 'staff_jobs')], default=account.account_type.StaffGroupType('staff_verification'), max_length=60),
        ),
    ]
