# Generated by Django 2.2.10 on 2020-04-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200404_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=120)),
                ('street_number', models.IntegerField()),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='defaultaccount',
            name='facility_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Address'),
        ),
        migrations.AlterField(
            model_name='employeraccount',
            name='company_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Address'),
        ),
    ]
