# Generated by Django 2.2.10 on 2020-03-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_staffaccount_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='group_type',
            field=models.CharField(choices=[('staff_verification', 'staff_verification'), (2, 'staff_cv'), (3, 'staff_jobs')], default='staff_verification', max_length=60),
        ),
    ]
