# Generated by Django 2.2.8 on 2020-02-12 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_employeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeraccount',
            name='nip',
            field=models.CharField(default='sdfsdf', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
