# Generated by Django 2.2.10 on 2020-04-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_staffaccount_group_type'),
        ('account', '0003_auto_20200421_2254'),
    ]

    operations = [
    ]
