# Generated by Django 2.2.10 on 2020-05-10 15:16

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_20200425_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=account.models.EmailLowerCaseField(max_length=60, unique=True, verbose_name='email'),
        ),
    ]
