# Generated by Django 2.2.10 on 2020-05-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200510_2214'),
        ('account', '0005_auto_20200510_1716'),
    ]

    operations = [
    ]
