# Generated by Django 2.2.10 on 2020-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200510_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, 'Verified'), (2, 'Waiting for verification'), (3, 'Rejected'), (4, 'Blocked')], default=2),
        ),
    ]
