# Generated by Django 2.2.10 on 2020-05-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200515_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, 'verified'), (2, 'waiting_for_verification'), (3, 'rejected'), (4, 'blocked')], default=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'standard'), (2, 'staff'), (3, 'employer')], default=1),
        ),
    ]
