# Generated by Django 2.2.10 on 2020-05-17 11:20

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200516_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=account.utils.create_profile_picture_file_path),
        ),
    ]
