# Generated by Django 2.2.10 on 2020-05-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='role',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
