# Generated by Django 2.2.10 on 2020-05-24 08:39

import account.utils
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_staffaccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(null=True, verbose_name='dołączył'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='ostatnio zalogowany'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=account.utils.create_profile_picture_file_path, verbose_name='zdjęcie profilowe'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='nazwa użytkownika'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=40, verbose_name='nazwa miasta'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=120, verbose_name='ulica'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(max_length=20, verbose_name='numer budynku'),
        ),
        migrations.AlterField(
            model_name='defaultaccount',
            name='facility_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Address', verbose_name='adres placówki'),
        ),
        migrations.AlterField(
            model_name='defaultaccount',
            name='facility_name',
            field=models.CharField(max_length=60, verbose_name='nazwa placówki'),
        ),
        migrations.AlterField(
            model_name='defaultaccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='numer telefonu'),
        ),
        migrations.AlterField(
            model_name='employeraccount',
            name='company_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Address', verbose_name='adres firmy'),
        ),
        migrations.AlterField(
            model_name='employeraccount',
            name='company_name',
            field=models.CharField(max_length=60, verbose_name='nazwa firmy'),
        ),
        migrations.AlterField(
            model_name='employeraccount',
            name='nip',
            field=models.CharField(max_length=10, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='employeraccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='numer telefonu'),
        ),
    ]
