# Generated by Django 2.2.10 on 2020-05-24 10:10

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200524_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'konto'},
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=account.models.EmailLowerCaseField(error_messages={'unique': 'Założono już konto na ten adres email.'}, max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'Nazwa użytkownika jest już zajęta.'}, max_length=30, unique=True, verbose_name='nazwa użytkownika'),
        ),
    ]
