# Generated by Django 2.2.10 on 2020-05-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcategory',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
