# Generated by Django 2.2.10 on 2020-05-18 20:08

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategory',
            name='header',
            field=models.ImageField(null=True, upload_to=blog.utils.create_category_header_file_path),
        ),
    ]
