# Generated by Django 2.2.10 on 2020-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200404_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(default=models.TextField(), null=True),
        ),
    ]
