# Generated by Django 2.2.10 on 2020-04-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200407_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='summary',
            new_name='_summary',
        ),
    ]
