# Generated by Django 2.2.7 on 2019-12-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='cv',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='cv.CV'),
        ),
    ]
