# Generated by Django 2.2.8 on 2020-02-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cv.CV'),
        ),
    ]
