# Generated by Django 2.2.7 on 2019-12-03 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='picture',
        ),
        migrations.AddField(
            model_name='school',
            name='additional_info',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to='cv_pictures/')),
                ('date_of_birth', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=12)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CV')),
            ],
        ),
    ]
