# Generated by Django 2.2.7 on 2019-12-03 21:42

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20191203_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='language',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='school',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='cv',
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_end',
            field=models.PositiveIntegerField(default=2019, null=True, validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='school',
            name='additional_info',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_end',
            field=models.PositiveIntegerField(default=2019, null=True, validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
    ]
