# Generated by Django 2.2.10 on 2020-04-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200406_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='was_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
