# Generated by Django 2.2.7 on 2019-12-06 15:47

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20191206_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year_end',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_end',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
    ]
