# Generated by Django 2.2.8 on 2020-02-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200218_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='basic_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='experiences',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='schools',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
