# Generated by Django 2.2.10 on 2020-04-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cv_was_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='wants_verification',
        ),
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
