# Generated by Django 2.2.7 on 2019-12-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20191203_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.AddField(
            model_name='cv',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
