# Generated by Django 2.2.8 on 2020-01-07 01:07

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20191206_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year_start',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_start',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
    ]
