# Generated by Django 2.2.10 on 2020-04-17 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cv_was_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
