# Generated by Django 2.2.10 on 2020-03-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200218_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='additional_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
