# Generated by Django 2.2.7 on 2019-12-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20191203_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='cv.CV'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv.CV'),
        ),
        migrations.AddField(
            model_name='language',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.CV'),
        ),
        migrations.AddField(
            model_name='school',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='cv.CV'),
        ),
        migrations.AddField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.CV'),
        ),
    ]
