# Generated by Django 2.2.10 on 2020-04-22 22:46

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cv_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='wants_verification',
        ),
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_start',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_start',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
    ]
