# Generated by Django 2.2.10 on 2020-04-19 20:46

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200419_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year_start',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_start',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), cv.models.max_value_current_year]),
        ),
    ]
