# Generated by Django 2.2.10 on 2020-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200423_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='has_picture',
            field=models.BooleanField(default=False),
        ),
    ]
