# Generated by Django 2.2.10 on 2020-05-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_cv_has_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='template',
            field=models.CharField(default='lightblue', max_length=40),
            preserve_default=False,
        ),
    ]
