# Generated by Django 2.2.10 on 2020-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_cv_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='year_start',
        ),
        migrations.RemoveField(
            model_name='school',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='school',
            name='year_start',
        ),
        migrations.AddField(
            model_name='experience',
            name='date_end',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_start',
            field=models.CharField(default='01-2000', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='date_end',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='date_start',
            field=models.CharField(default='01-2000', max_length=7),
            preserve_default=False,
        ),
    ]
