# Generated by Django 2.2.10 on 2020-05-24 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('seen', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('video', models.URLField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='steps.Step')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steps.Step')),
            ],
            options={
                'abstract': False,
            },
            bases=('steps.step',),
        ),
        migrations.CreateModel(
            name='UserPerspective',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.DefaultAccount')),
                ('substep_order', models.PositiveIntegerField(default=0)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='steps.Step')),
            ],
        ),
        migrations.CreateModel(
            name='SubStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('seen', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('video', models.URLField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substeps', to='steps.Step')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
