# Generated by Django 2.2.10 on 2020-05-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_profile_picture'),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerspective',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.DefaultAccount')),
                ('substep_order', models.PositiveIntegerField()),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='steps.Step')),
            ],
        ),
    ]
