# Generated by Django 2.2.10 on 2020-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='substep',
            name='seen',
        ),
        migrations.AddField(
            model_name='substep',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
