# Generated by Django 2.2.10 on 2020-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_auto_20200522_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='substep',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
