# Generated by Django 2.2.10 on 2020-04-04 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferCategory',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=70)),
                ('company_address', models.CharField(max_length=200)),
                ('voivodeship', models.CharField(choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świętokrzyskie', 'świętokrzyskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=30)),
                ('expiration_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('removed', models.BooleanField(default=False, editable=False)),
                ('category', models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobOfferCategory')),
                ('employer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.EmployerAccount')),
                ('interested_users', models.ManyToManyField(to='account.DefaultAccount')),
                ('offer_type', models.ForeignKey(db_column='offer_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobOfferType')),
            ],
        ),
    ]
