# Generated by Django 2.2.10 on 2020-04-05 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0001_initial'),
        ('account', '0002_auto_20200404_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=70)),
                ('company_address', models.CharField(max_length=200)),
                ('voivodeship', models.CharField(choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świętokrzyskie', 'świętokrzyskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=30)),
                ('expiration_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('removed', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferCategory',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_cv', to='cv.CV')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobOffer')),
            ],
        ),
        migrations.AddField(
            model_name='joboffer',
            name='category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobOfferCategory'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.EmployerAccount'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_type',
            field=models.ForeignKey(db_column='offer_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobOfferType'),
        ),
    ]
