# Generated by Django 2.2.10 on 2020-05-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='zip_file',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='jobofferapplication',
            name='document',
            field=models.FileField(null=True, upload_to='application_docs/'),
        ),
    ]
