# Generated by Django 2.2.8 on 2020-03-14 10:55

from django.db import migrations, models
import uuid


def fill_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    JobOfferModel = apps.get_model('job', 'JobOffer')
    for obj in JobOfferModel.objects.using(db_alias).all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('job', '0002_auto_20200303_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_uuid, migrations.RunPython.noop),
        migrations.RunSQL(
            "ALTER TABLE job_joboffer_interested_users ADD COLUMN joboffer_uuid uuid NULL;"
            "UPDATE job_joboffer_interested_users SET joboffer_uuid = o.uuid FROM job_joboffer AS o WHERE joboffer_id = o.id;"
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, unique=True),
        ),
        migrations.RemoveField('joboffer', 'id'),
        migrations.RenameField(
            model_name='joboffer',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False),
        ),
        migrations.RunSQL(
            "ALTER TABLE job_joboffer_interested_users DROP COLUMN joboffer_id;"
            "ALTER TABLE job_joboffer_interested_users RENAME COLUMN joboffer_uuid TO joboffer_id;"
            "ALTER TABLE job_joboffer_interested_users ADD CONSTRAINT job_joboffer_interes_joboffer_id_fk_job_jobof FOREIGN KEY (joboffer_id) REFERENCES job_joboffer(id);"
        ),
    ]
