# Generated by Django 2.2.10 on 2020-05-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_joboffer_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='salary_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
