# Generated by Django 2.2.10 on 2020-05-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200517_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary_max',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_min',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
