# Generated by Django 2.2.10 on 2020-05-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.BooleanField(default=False)),
                ('top', models.BooleanField(default=False)),
                ('right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='tiles/%Y/%m/%d')),
                ('destination', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('photo_layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tiles.PhotoLayer')),
            ],
        ),
    ]
