# Generated by Django 2.2.10 on 2020-05-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='color',
            field=models.CharField(default='niebieski', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='destination',
            field=models.CharField(default='costam', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='photo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='photo_layer_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='photo_layer_top',
            field=models.BooleanField(default=False),
        ),
    ]
