# Generated by Django 2.2.10 on 2020-05-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0002_auto_20200525_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='title',
            field=models.CharField(default='tytul', max_length=100),
            preserve_default=False,
        ),
    ]
